<?php

namespace Database\Seeders;

use App\Models\Facility;
use App\Models\User;
use Illuminate\Database\Seeder;

class FacilitiesSeeder extends Seeder
{
    public function run(): void
    {
        // Get the admin user to assign as facility owner
        $adminUser = User::where('email', 'marcin-gantkowski@outlook.com')->first();
        
        if (!$adminUser) {
            $this->command->error('Admin user not found. Please ensure marcin-gantkowski@outlook.com exists.');
            return;
        }

        $facilities = [
            [
                'name' => 'Fundacja Synapsis',
                'address' => "ul. Ondraszka 3\r\n02-085 Warszawa",
                'phone' => '(+ 48 22) 825 87 42',
                'email' => 'fundacja@synapsis.org.pl',
                'website' => 'https://synapsis.org.pl/',
                'description' => "Misją Fundacji SYNAPSIS jest niesienie profesjonalnej pomocy dzieciom i dorosłym osobom z autyzmem i ich rodzinom oraz wypracowywanie systemowych rozwiązań, które poprawią jakość ich życia.\r\n\r\nDecyzją z dnia 6 marca 2024 roku Wojewoda Mazowiecki przyznał Fundacji SYNAPSIS status przedsiębiorstwa społecznego prowadzącego działalność, która ma na celu realizację usług społecznych.",
            ],
            [
                'name' => 'Stowarzyszenie Innowacji Społecznych Mary&Max',
                'address' => "ul. Marszałkowska 84/92 lok. 201\r\n00-514 Warszawa",
                'phone' => '+ 48 516 735 521',
                'email' => 'kontakt@maryimax.pl',
                'website' => 'https://maryimax.pl/',
                'description' => 'Placówka zapewnia wsparcie dla młodzieży(od 14 lat) i dorosłych w spektrum autyzmu organizując warsztaty rozwijania umiejętności społecznych, klub spotkań oraz wolontariat koleżeński',
            ],
            [
                'name' => 'Szpital dla Nerwowo i Psychicznie Chorych',
                'address' => 'al.Tysiąclecia 30, 59-700 Bolesławiec',
                'phone' => '756162648',
                'email' => 'sekretariat@szpitalpsychiatryczny.pl',
                'website' => 'https://www.szpitalpsychiatryczny.pl',
                'description' => '',
            ],
            [
                'name' => 'Niepubliczny Zakład Opieki Zdrowotnej',
                'address' => 'ul. Księdza Emila Pagacza 6, 58-250 Pieszyce',
                'phone' => '748175270',
                'email' => 'amdorozala@scz.com.pl',
                'website' => '',
                'description' => '',
            ],
            [
                'name' => 'Niepubliczny Zakład Opieki Zdrowotnej',
                'address' => 'ul. Senatoryjna 15, 58-530 Kowary',
                'phone' => '756415715',
                'email' => 'sekretariat@pcz-kowary.pl',
                'website' => 'https://www.emc-sa.pl/nasze-placowki/kowary-szpital-bukowiec',
                'description' => '',
            ],
            [
                'name' => 'Centrum Psychoprofilatyki i Terapii "PRO-MAIND" Michał Behnke',
                'address' => ' 160, 58-535 Miłków',
                'phone' => '694949317',
                'email' => 'info@promaind.pl',
                'website' => 'https://www.promaind.pl',
                'description' => '',
            ],
            [
                'name' => 'Centrum Psychoprofilatyki i Terapii "PRO-MAIND"-Hostele',
                'address' => 'ul. Muflonowa 4, 58-564 Sosnówka',
                'phone' => '694949317',
                'email' => 'info@promaind.pl',
                'website' => 'https://www.promaind.pl',
                'description' => '',
            ],
            [
                'name' => 'Stowarzyszenie Monar Ośrodek Leczenia, Terapii i Rehabilitacji Uzależnień w Mysłakowicach',
                'address' => 'Czerwony Dworek 5, 58-533 Mysłakowice',
                'phone' => '757131537',
                'email' => 'czerwonydworek@monar.org',
                'website' => 'https://monar.org.pl',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzkie Centrum Psychiatrii Długoterminowej w Stroniu Śląskim',
                'address' => 'ul. Sudecka 3A, 57-500 Stronie Śląskie',
                'phone' => '748141488',
                'email' => 'szpital_stronie@pro.onet.pl',
                'website' => 'https://wcpd.pl/bip/',
                'description' => '',
            ],
            [
                'name' => 'Zespół Opieki Zdrowotnej w Kłodzku',
                'address' => 'ul. Szpitalna 1a, 57-300 Kłodzko',
                'phone' => '748651201',
                'email' => 'sekretariat@zoz.klodzko.pl',
                'website' => 'https://www.zoz.klodzko.pl',
                'description' => '',
            ],
            [
                'name' => 'Ośrodek Badawczo - Naukowy - Dydaktyczny Chorób Otępiennych im. Księdza Henryka Kardynała Gulbinowicza Uniwersytetu Medycznego. Ośrodek Altzheimerowski Sp. z o.o.',
                'address' => 'ul. Jana Pawła II 12, 59-330 Ścinawa',
                'phone' => '768491665',
                'email' => 'sekretariat@osrodek-alzheimer.pl',
                'website' => 'https://osrodek-alzheimer.pl',
                'description' => '',
            ],
            [
                'name' => 'Milickie Centrum Medyczne Sp. z o.o.',
                'address' => 'ul. Grzybowa 1, 56-300 Milicz',
                'phone' => '713846754',
                'email' => 'sekretariat@mcm-milicz.pl',
                'website' => 'https://www.mcm-milicz.pl',
                'description' => '',
            ],
            [
                'name' => 'Zakład Leczenia Odwykowego dla Osób Uzależnionych od Alkoholu w Czarnym Borze',
                'address' => 'ul. Parkowa 8, 58-379 Czarny Bór',
                'phone' => '748450125',
                'email' => 'biuro@zlo.czarnybor.pl',
                'website' => 'https://zlo.czarnybor.pl',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Szpital dla Nerwowo i Psychicznie Chorych w Lubiążu',
                'address' => 'ul. Adama Mickiewicza 1, 56-100 Wołów',
                'phone' => '713897499',
                'email' => 'lubszpital@onet.pl',
                'website' => 'https://lubszpital.pl',
                'description' => '',
            ],
            [
                'name' => 'Zakład Psychiatryczny dla Nerwowo i Psychicznie Chorych w Sieniawce im. Dr M. Marzyńskiego',
                'address' => 'ul. Rolnicza 25, 59-921 Sieniawka',
                'phone' => '756494700',
                'email' => 'szpitalsieniawka@pro.onet.pl',
                'website' => 'https://www.spzoz.zgorzelec.pl',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Szpital Psychiatryczny w Złotoryi',
                'address' => 'ul. Szpitalna 9, 59-500 Złotoryja',
                'phone' => '768779300',
                'email' => 'sekretariat.wszp@gmail.com',
                'website' => 'https://wsp.szpitalna9.pl',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Szpital Psychiatryczny w Złotoryi',
                'address' => 'ul. Chojnowska 81, 59-220 Legnica',
                'phone' => '768779300',
                'email' => 'sekretariat.wszp@gmail.com',
                'website' => 'https://wsp.szpitalna9.pl',
                'description' => '',
            ],
            [
                'name' => 'Ośrodek Terapii Uzależnień NADZIEJA',
                'address' => 'ul. Wrocławska 16, 55-095 Siedlec',
                'phone' => '',
                'email' => 'info@nzoznadzieja.pl',
                'website' => '',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Zakład Opieki Zdrowotnej Ministerstwa Spraw Wewnętrznych w Jeleniej Górze',
                'address' => 'ul. Cieplicka 69/71, 58-560 Jelenia Góra',
                'phone' => '756435700',
                'email' => 'sekretariat@szpitalmsw.net',
                'website' => 'https://www.szpitalmsw.net',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Szpital Specjalistyczny w Legnicy',
                'address' => 'ul. Jarosława Iwaszkiewicza 5, 59-220 Legnica',
                'phone' => '767211000',
                'email' => 'psychiatria@szpital.legnica.pl',
                'website' => 'https://szpital.legnica.pl',
                'description' => '',
            ],
            [
                'name' => 'Oddział psychiatryczny',
                'address' => 'ul. Świebodzka 1, 50-046 Wrocław',
                'phone' => '713272400',
                'email' => 'as_wroclaw@sw.gov.pl',
                'website' => 'https://www.sw.gov.pl/jednostka/areszt-sledczy-we-wroclawiu',
                'description' => '',
            ],
            [
                'name' => 'Dolnośląskie Centrum Zdrowia Psychicznego Sp. z o.o.',
                'address' => 'wyb. Józefa Conrada-Korzeniowskiego 18, 50-226 Wrocław',
                'phone' => '717766212',
                'email' => 'sekretariat@dczp.wroclaw.pl',
                'website' => 'https://dczp.wroclaw.pl',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Szpital Specjalistyczny in. J. Gromkowskiego',
                'address' => 'ul. Koszarowa 5, 51-149 Wrocław',
                'phone' => '713261325',
                'email' => 'gromkowski@szpital.wroc.p',
                'website' => 'https://www.szpital.wroc.pl',
                'description' => '',
            ],
            [
                'name' => '4 Wojskowy Szpital Kliniczny z Polikliniką Samodzienlny Publiczny Zakład Opieki Zdrowotnej we Wrocławiu',
                'address' => 'ul. Rudolfa Weigla 5, 50-981 Wrocław',
                'phone' => '261660723',
                'email' => 'szpital@4wsk.pl',
                'website' => 'https://www.4wsk.pl',
                'description' => '',
            ],
            [
                'name' => 'Katedra Psychiatrii Uniwersytetu Medycznego we Wrocławiu',
                'address' => 'ul. Wybrzeże L. Laustera 10, 50-367 Wrocław',
                'phone' => '717331100',
                'email' => 'psychiatria@umed.wroc.pl',
                'website' => 'https://www.usk.wroc.pl/',
                'description' => '',
            ],
            [
                'name' => 'Stowarzyszenie Monar - Ośrodek Leczenia, Terapii i Rehabilitacji Uzależnień We Wrocławiu',
                'address' => 'ul. Jarzębinowa 14/16, 53-120 Wrocław',
                'phone' => '717841600',
                'email' => 'roosvelta-monar@wp.pl',
                'website' => 'https://www.monar.org',
                'description' => '',
            ],
            [
                'name' => 'Ośrodek Medycyny Paliatywnej i Hospicyjnej Będkowo Sp. z o.o.',
                'address' => 'Będkowo 1, 55-100 Będkowo',
                'phone' => '717222948',
                'email' => 'sekretariat@hospicjumbedkowo.pl',
                'website' => 'https://www.hospicjumbedkowo.pl/',
                'description' => '',
            ],
            [
                'name' => 'Ośrodek Terapii Uzależnienia i Współuzależnienia "Radzimowice',
                'address' => 'ul. Dolna 4, 58-580 Szklarska Poręba',
                'phone' => '757174722',
                'email' => 'radzimowice@radzimowice.pl',
                'website' => 'https://radzimowice.pl',
                'description' => '',
            ],
            [
                'name' => 'Ośrodek Terapii Uzależnień TERRA',
                'address' => 'Grzebielin 6c, 56-330 Grzebielin',
                'phone' => '713830383',
                'email' => '',
                'website' => 'https://grzebielin.pl/',
                'description' => '',
            ],
            [
                'name' => 'Specjalistyczny Szpital im. Dra Alfreda Sokołowskiego',
                'address' => 'ul. Stefana Batorego 4, 58-309 Wałbrzych',
                'phone' => '746489600',
                'email' => 'szpitalsokolowski@zdrowie.walbrzych.pl',
                'website' => 'https://www.zdrowie.walbrzych.pl',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Szpital dla Nerwowo i Psychicznie Chorych w Świeciu',
                'address' => 'ul. Sądowa 18, 86-100 Świecie',
                'phone' => '523308305',
                'email' => 'sekretariat@szpital-psychiatryczny.swiecie.pl',
                'website' => 'https://www.szpital-psychiatryczny.swiecie.pl/',
                'description' => '',
            ],
            [
                'name' => 'Centrum Medyczne Gizińscy Sp. z o.o. w Bydgoszczy',
                'address' => 'ul. Leśna 9a, 85-676 Bydgoszcz',
                'phone' => '605300155',
                'email' => 'office@gizinscy.pl',
                'website' => 'https://www.gizinscy.pl/',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Szpital Zespolony im. L. Rydygiera w Toruniu',
                'address' => 'ul. Marii Skłodowskiej-Curie 27/29, 87-100 Toruń',
                'phone' => '566793500',
                'email' => 'sekretariat@wszz.torun.pl',
                'website' => 'https://www.wszz.torun.pl/',
                'description' => '',
            ],
            [
                'name' => 'Regionalny Szpital Specjalistyczny im. dr. Wł. Biegańskiego w Grudziądzu',
                'address' => 'ul. Rydygiera 15, 86-300 Grudziądz',
                'phone' => '566413400',
                'email' => 'sekretariat.dyrekcja@bieganski.org',
                'website' => 'https://bieganski.org/pl/main',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Zakład Opieki Zdrowotnej w Radziejowie',
                'address' => 'ul. Szpitalna 3, 88-200 Radziejów',
                'phone' => '542856200',
                'email' => 'poczta@szpitalradziejow.pl',
                'website' => 'https://www.szpitalradziejow.pl',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Ośrodek Terapii Uzależnień i Współuzależnienia w Toruniu',
                'address' => 'ul. Szosa Bydgoska 1, 87-100 Toruń',
                'phone' => '566228908',
                'email' => 'wotuiw@wotuiw.torun.pl',
                'website' => 'https://www.wotuiw.torun.pl/',
                'description' => '',
            ],
            [
                'name' => 'Powiatowy Szpital w Aleksandrowie Kujawskim Sp. z o.o.',
                'address' => 'ul. Słowackiego 18, 87-700 Aleksandrów Kujawski',
                'phone' => '542828001',
                'email' => 'spzcal@poczta.onet.pl',
                'website' => 'https://www.szpital-aleksandrow.internetdsl.pl',
                'description' => '',
            ],
            [
                'name' => 'Szpital Lipno Sp. z o.o. w Lipnie',
                'address' => 'ul. Nieszawska 6, 87-600 Lipno',
                'phone' => '542880331',
                'email' => 'szpitallipno@pro.onet.pl',
                'website' => 'https://www.szpitallipno.pl/',
                'description' => '',
            ],
            [
                'name' => 'Ośrodek Terapii Uzależnień Cedr - Mokowo',
                'address' => 'Mokowo 37, 87-610 Mokowo',
                'phone' => '500123058',
                'email' => 'terapia@cedr-osrodek.pl',
                'website' => 'https://cedr-osrodek.pl/',
                'description' => '',
            ],
            [
                'name' => '10 Wojskowy Szpital Kliniczny z Polikliniką w Bydgoszczy',
                'address' => 'ul. Powstańców Warszawy 5, 85-681 Bydgoszcz',
                'phone' => '261417220',
                'email' => 'szpital@10wsk.mil.pl',
                'website' => 'https://www.10wsk.mil.pl/pl/',
                'description' => '',
            ],
            [
                'name' => 'Szpital Uniwersytecki nr 1 im. dr. A. Jurasza w Bydgoszczy',
                'address' => 'ul. Skłodowskiej-Curie 9, 85-094 Bydgoszcz',
                'phone' => '525854000',
                'email' => 'sekretariat@jurasza.pl',
                'website' => 'https://jurasza.umk.pl/',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Zakład Leczniczo-Opiekuńczy w Raciążku',
                'address' => 'ul. Przedmiejska 1, 87-721 Raciążek',
                'phone' => '542831000',
                'email' => 'spzlo@spzlo-raciazek.pl',
                'website' => 'https://www.spzlo-raciazek.pl',
                'description' => '',
            ],
            [
                'name' => 'Zakład Pielęgnacyjno-Opiekuńczy im. Ks. J. Popiełuszki w Toruniu',
                'address' => 'ul. Ligi Polskiej 8, 87-100 Toruń',
                'phone' => '566574290',
                'email' => 'zpo@zpotorun.pl',
                'website' => 'https://www.zpotorun.pl/',
                'description' => '',
            ],
            [
                'name' => 'I Klinika Psychiatrii, Psychoterapii i Wczesnej Interwencji; II Klinika Psychiatrii i Rehabilitacji Psychiatrycznej',
                'address' => 'Głuska 1, 20-439 Lublin',
                'phone' => '817487307',
                'email' => 'szpital@spsk1.lublin.pl',
                'website' => 'https://www.spsk1.lublin.pl',
                'description' => '',
            ],
            [
                'name' => 'Szpital Neuropsychiatryczny im. prof. M. Kaczyńskiego SPZOZ',
                'address' => 'ul. Abramowicka 2, 20-442 Lublin',
                'phone' => '817441079',
                'email' => 'sekretariat@snzoz.lublin.pl',
                'website' => 'https://www.snzoz.lublin.pl',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Zespół Zakładów Opieki Zdrowotnej w Janowie Lubelskim',
                'address' => 'ul. Jana Zamoyskiego 149, 23-300 Janów Lubelski',
                'phone' => '158436611',
                'email' => 'sekretariat@szpitaljanowlubelski.pl',
                'website' => 'https://www.szpitaljanowlubelski.pl',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Zakład Opieki Zdrowotnej w Łukowie',
                'address' => 'ul. Doktora Andrzeja Rogalińskiego 3, 21-400 Łuków',
                'phone' => '257982603',
                'email' => 'spzoz@spzoz.lukow.pl',
                'website' => 'https://spzoz.lukow.pl',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Zakład Opieki Zdrowotnej w Parczewie',
                'address' => 'ul. Kościelna 136, 21-200 Parczew',
                'phone' => '833552102',
                'email' => 'sekretariat@spzozparczew.pl',
                'website' => 'https://www.spzozparczew.pl',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Zakład Opieki Zdrowotnej w Radzyniu Podlaskim',
                'address' => 'ul. Wisznica 111, 21-300 Radzyń Podlaski',
                'phone' => '834132267',
                'email' => 'sekretariat@spzozrp.pl',
                'website' => 'https://spzozrp.pl',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Szpital dla Nerwowo i Psychicznie Chorych w Suchowoli',
                'address' => 'Kuraszew 48, 21-210 Kuraszew',
                'phone' => '833530363',
                'email' => 'sekretariat-suchowola@o2.pl',
                'website' => 'https://szpitalsuchowola.pl',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Wojewódzki Szpital Specjalistyczny w Chełmie',
                'address' => 'ul. Ceramiczna 1, 22-100 Chełm',
                'phone' => '825623223',
                'email' => 'szpital@szpital.chelm.pl',
                'website' => 'https://www.szpital.chelm.pl',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Zespół Opieki Zdrowotnej w Hrubieszowie',
                'address' => 'ul. Piłsudskiego 11, 22-500 Hrubieszów',
                'phone' => '846962611',
                'email' => 'sekretariat@spzozhrubieszow.pl',
                'website' => 'https://www.spzozhrubieszow.pl',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Wojewódzki Szpital Psychiatryczny w Radecznicy',
                'address' => 'ul. Klasztorna 4, 22-463 Radecznica',
                'phone' => '846818841',
                'email' => 'poczta@radecznica.pl',
                'website' => 'https://radecznica.pl',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Psychiatryczny Zakład Opiekuńczo - Leczniczy w Celejowie',
                'address' => 'Celejów 68, 24-120 Celejów',
                'phone' => '818810211',
                'email' => 'sekretariat@spzolcelejow.pl',
                'website' => 'https://www.spzolcelejow.pl',
                'description' => '',
            ],
            [
                'name' => 'Niepubliczny Zakład Opieki Zdrowotnej KAMIMED A. Kamińska, M. Kamiński s.c. Zakład Opiekuńczo-Leczniczy Psychiatryczny',
                'address' => 'ul. Nowa 1A, 21-210 Milanów',
                'phone' => '667003700',
                'email' => 'kamimedzol@gmail.com',
                'website' => 'https://www.kamimed.pl',
                'description' => '',
            ],
            [
                'name' => 'Stowarzyszenie Monar Ośrodek Leczenia, Terapii i Rehabilitacji Uzależnień w Majdanie Kozic Dolnych',
                'address' => 'Majdan Kozic Dolnych 29, 21-050 Piaski',
                'phone' => '815847042',
                'email' => 'majdan29monar@wp.pl',
                'website' => 'https://www.makondo.monar.org',
                'description' => '',
            ],
            [
                'name' => 'Niepubliczny Zakład Opieki Zdrowotnej Ośrodek Rehabilitacyjny dla Uzależnionych Od Substancji Psychoaktywnych Młodzieżowy Ośrodek Terapii i Readaptacji  "Powrót z U',
                'address' => 'Albrechtówka 5, 24-120 Kazimierz Dolny',
                'phone' => '818810014',
                'email' => 'powrotzu.cholewianka@gmail.com',
                'website' => 'https://powrotzu.pl',
                'description' => '',
            ],
            [
                'name' => '"Zielona Klinika" Ośrodek Leczenia i Rehabilitacji Zaburzeń Psychosomatycznych i Uzależnień',
                'address' => 'Uniszowice 57G, 21-030 Uniszowice',
                'phone' => '601388414',
                'email' => 'waldemar.olech@neostrada.pl',
                'website' => '',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Szpital Specjalistyczny dla Nerwowo i Psychicznie Chorych Samodzielny Publiczny ZOZ w Ciborzu',
                'address' => 'Cibórz 5, 66-213 Cibórz',
                'phone' => '683419350',
                'email' => 'szpital@ciborz.eu',
                'website' => 'https://www.ciborz.eu',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Szpital dla Nerwowo i Psychicznie Chorych w Międzyrzeczu',
                'address' => 'ul. Poznańska 109, 66-300 Międzyrzecz',
                'phone' => '957428700',
                'email' => 'sekretariat@obrzyce.eu',
                'website' => 'https://www.obrzyce.eu',
                'description' => '',
            ],
            [
                'name' => 'Wielospecjalistyczny Szpital Wojewódzki w Gorzowie Wlkp. spółka z ograniczoną odpowiedzialnością',
                'address' => 'ul. Franciszka Walczaka 42, 66-400 Gorzów Wielkopolski',
                'phone' => '957331600',
                'email' => 'sekretariat@szpital.gorzow.pl',
                'website' => 'https://www.szpital.gorzow.pl',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Zakład Opieki Zdrowotnej Centrum Leczenia Dzieci i Młodzieży w Zaborze',
                'address' => 'ul. Zamkowa 1, 66-003 Zabór',
                'phone' => '683274028',
                'email' => 'biuro@cldim.zgora.pl',
                'website' => 'https://www.cldim.zgora.pl',
                'description' => '',
            ],
            [
                'name' => 'Ośrodek dla Osób Uzależnionych Samodzielny Publiczny Zakład Opieki Zdrowotnej ,,Nowy Dworek',
                'address' => 'Glińsk 36, 66-200 Glińsk',
                'phone' => '683810167',
                'email' => 'sekretariat@nowydworek.com',
                'website' => 'https://www.nowydworek.com',
                'description' => '',
            ],
            [
                'name' => 'Ośrodek dla Osób Uzaleznionych SP ZOZ',
                'address' => 'Nowy Dworek , 66-200 Nowy Dworek',
                'phone' => '683810167',
                'email' => 'sekretariat@nowydworek.com',
                'website' => 'https://www.nowydworek.com',
                'description' => '',
            ],
            [
                'name' => 'Ośrodek dla Osób Uzależnionych Samodzielny Publiczny Zakład Opieki Zdrowotnej ,,Nowy Dworek',
                'address' => 'Jordanowo 53, 66-200 Świebodzin',
                'phone' => '683810167',
                'email' => 'sekretariat@nowydworek.com',
                'website' => 'https://www.nowydworek.com',
                'description' => '',
            ],
            [
                'name' => 'Ośrodek dla Osób Uzależnionych Samodzielny Publiczny Zakład Opieki Zdrowotnej ,,Nowy Dworek',
                'address' => 'ul. Mała 5, 66-200 Świebodzin',
                'phone' => '683810167',
                'email' => 'sekretariat@nowydworek.com',
                'website' => 'https://www.nowydworek.com',
                'description' => '',
            ],
            [
                'name' => '105. Kresowy Szpital Wojskowy z Przychodnią Samodzielny Publiczny Zakład Opieki Zdrowotnej w Żarach',
                'address' => 'ul. Domańskiego 2, 68-200 Żary',
                'phone' => '684707810',
                'email' => '',
                'website' => 'https://www.105szpital.pl',
                'description' => '',
            ],
            [
                'name' => 'Katolicki Ośrodek Terapii i Wychowania Młodzieży Anastasis',
                'address' => 'Strychy 42, 66-340 Strychy',
                'phone' => '957493073',
                'email' => 'strychy@gmail.com',
                'website' => 'https://www.narkomania.net',
                'description' => '',
            ],
            [
                'name' => 'Stowarzyszenie Pomocy Młodzieży "Anastasis',
                'address' => 'Nowy Dwór 10, 66-400 Nowy Dwór',
                'phone' => '957493073',
                'email' => 'strychy@gmail.com',
                'website' => 'https://www.narkomania.net',
                'description' => '',
            ],
            [
                'name' => 'Specjalistyczny Psychiatryczny Zespół Opieki Zdrowotnej w Łodzi, Szpital im. dr. J. Babińskiego',
                'address' => 'ul. Aleksandrowska 159, 91-229 Łódź',
                'phone' => '426529401',
                'email' => 'sekretariat@babinski.home.pl',
                'website' => 'https://www.babinski.home.pl/',
                'description' => '',
            ],
            [
                'name' => 'Samodzielny Publiczny Zakład Opieki Zdrowotnej Centralny Szpital Kliniczny Uniwersytetu Medycznego w Łodzi',
                'address' => 'ul. Pomorska 51, 92-213 Łódź',
                'phone' => '426757272',
                'email' => 'poczta@csk.umed.pl',
                'website' => 'https://www.csk.umed.pl/',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Szpital Specjalistyczny im. Marii Skłodowskiej-Curie w Zgierzu',
                'address' => 'ul. Parzęczewska 35, 95-100 Zgierz',
                'phone' => '427144500',
                'email' => 'szpital@wss.zgierz.pl',
                'website' => 'https://szpital.zgierz.pl/',
                'description' => '',
            ],
            [
                'name' => 'Centrum Psychiatryczne w Warcie',
                'address' => 'ul. Sieradzka 3, 98-290 Warta',
                'phone' => '438294013',
                'email' => 'szpitalwarta@szpitalwarta.pl',
                'website' => 'https://www.szpitalwarta.regiony.pl/',
                'description' => '',
            ],
            [
                'name' => 'Zakład Opiekuńczo-Leczniczy',
                'address' => 'ul. Sieradzka 3, 98-290 Warta',
                'phone' => '438294013',
                'email' => 'szpitalwarta@szpitalwarta.pl',
                'website' => 'https://www.szpitalwarta.regiony.pl/',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Szpital im. Jana Pawła II w Bełachatowie',
                'address' => 'ul. Czapliniecka 123, 97-400 Bełchatów',
                'phone' => '446358200',
                'email' => 'szpital@szpital-belchatow.pl',
                'website' => 'https://www.szpital-belchatow.pl/',
                'description' => '',
            ],
            [
                'name' => 'Miejskie Centrum Terapi i Profilaktyki Zdrowotnej im. Bł.  Rafała Chylińskiego w Łodzi',
                'address' => 'ul. Niciarniana 41, 92-320 Łódź',
                'phone' => '426761734',
                'email' => 'mczp@mczp-lodz.pl',
                'website' => 'https://www.chylinskilodz.pl/',
                'description' => '',
            ],
            [
                'name' => 'Pabianickie Centrum Psychiatryczne',
                'address' => 'ul. Jana Pawła II 68, 95-200 Pabianice',
                'phone' => '422253500',
                'email' => 'pcmnzoz@pcmnzoz.pl',
                'website' => 'https://www.pcmnzoz.pl/',
                'description' => '',
            ],
            [
                'name' => 'Prywatna Klinika Psychiatryczna Inventiva',
                'address' => 'ul. Polna 16/20, 95-080 Tuszyn',
                'phone' => '426142623',
                'email' => 'sekretariat@klinika-inventiva.pl,',
                'website' => 'https://klinika-inventiva.pl/',
                'description' => '',
            ],
            [
                'name' => 'Tomaszowskie Centrum Zdrowia Sp. z o.o.',
                'address' => 'ul. Jana Pawła II 35, 97-200 Tomaszów Mazowiecki',
                'phone' => '447257134',
                'email' => 'sekretariat@tomaszow.org.pl',
                'website' => 'https://szpitalwtomaszowie.pl/',
                'description' => '',
            ],
            [
                'name' => 'Klinika Psychiatryczna i Terapii Uzależnień Klinika Wolmed Joanna Wyysogląd-Wolniak',
                'address' => 'Dubie 1a, 97-420 Dubie',
                'phone' => '446356303',
                'email' => 'sekretariat@wolmed.pl',
                'website' => 'https://www.wolmed.pl/',
                'description' => '',
            ],
            [
                'name' => 'Ośrodek Terapii Uzależnień To Tu Sp. z o.o.',
                'address' => 'Karnice 41, 99-200 Karnice',
                'phone' => '690425979',
                'email' => 'terapia@terapia-totu.pl',
                'website' => 'https://terapia-totu.pl/',
                'description' => '',
            ],
            [
                'name' => 'Niepubliczny Zakład Opieki Zdrowotnej Ośrodek Rehabilitacyjno-Readaptacyjny "Arka',
                'address' => 'Męcka Wola 48A, 98-200 Sieradz',
                'phone' => '438282201',
                'email' => 'fundacja.arka@wp.pl',
                'website' => 'https://www.fundacja-arka.org.pl/',
                'description' => '',
            ],
            [
                'name' => 'Stowarzyszenie Monar- Ośrodek Leczenia, Terapii i Rehabilitacji Uzależnień w Łodzi',
                'address' => 'ul. Tuszyńska 106, 93-305 Łódź',
                'phone' => '426464012',
                'email' => 'monarlodz@gmail.com',
                'website' => 'https://monartuszynska.pl/',
                'description' => '',
            ],
            [
                'name' => 'Hostel Dla Uzależnionych Od Substancji Psychoaktywnych',
                'address' => 'ul. Wólczańska 225, 93-005 Łódź',
                'phone' => '426842397',
                'email' => 'biuro@monar-kebliny.pl',
                'website' => 'https://www.hostel-lodz.eu/',
                'description' => '',
            ],
            [
                'name' => 'Stowarzyszenie Monar - Ośrodek Leczenia, Terapii i Rehabilitacji Uzależnień w Kęblinach',
                'address' => 'ul. Strykowska 3, 95-001 Biała',
                'phone' => '427178008',
                'email' => 'biuro@monar-kebliny.pl',
                'website' => 'https://www.monar-kebliny.pl/',
                'description' => '',
            ],
            [
                'name' => 'Stowarzyszenie Monar - Ośrodek Leczenia, Terapii i Rehabilitacji Uzależnień w Sokolnikach',
                'address' => 'ul. Różana 96, 95-039 Sokolniki',
                'phone' => '427101280',
                'email' => 'sokolniki@monar.org',
                'website' => 'https://monar-sokolniki.pl/',
                'description' => '',
            ],
            [
                'name' => 'Zakład Opiekuńczo-Leczniczy Towarzystwa Przyjaciół Niepełnosprawnych',
                'address' => 'ul. Jedlinowa 42/44, 95-073 Jedlicze',
                'phone' => '427179167',
                'email' => 'kontakt@tpn.org.pl',
                'website' => 'https://www.tpn.org.pl/',
                'description' => '',
            ],
            [
                'name' => 'Oddział psychiatryczny',
                'address' => 'ul. Józefa Ignacego Kraszewskiego 43470, 93-161 Łódź',
                'phone' => '426750701',
                'email' => 'dl_2_lodz@sw.gov.pl',
                'website' => 'https://www.sw.gov.pl/jednostka/zaklad-karny-nr-2-w-lodzi',
                'description' => '',
            ],
            [
                'name' => 'Szpital Kliniczny im. dr Józefa Babińskiego Samodzielny Publiczny Zakład Opieki Zdrowotnej',
                'address' => 'ul. Babińskiego 29, 30-393 Kraków',
                'phone' => '12524347',
                'email' => 'biuro@babinski.pl',
                'website' => 'https://babinski.pl/',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Szpital Specjalistyczny im. Ludwika Rydygiera Samodzielny Publiczny Zakład Opieki Zdrowotnej',
                'address' => 'Osiedle Złotej Jesieni 1, 31-826 Kraków',
                'phone' => '126468502',
                'email' => 'rydygier@rydygierkrakow.p/',
                'website' => 'https://www.szpitalrydygier.pl/',
                'description' => '',
            ],
            [
                'name' => 'Zespół Opieki Zdrowotnej w Oświęcimiu',
                'address' => 'ul. Wysokie Brzegi 4, 32-600 Oświęcim',
                'phone' => '338448200',
                'email' => 'dyrekcja@szpital.oswiecim.pl',
                'website' => 'https://www.szpital.oswiecim.pl',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Szpital Psychiatryczny w Andrychowie',
                'address' => 'ul. Dąbrowskiego 19, 34-120 Andrychów',
                'phone' => '338752446',
                'email' => 'szpital@szpital.info.pl',
                'website' => 'https://www.szpital.info.pl',
                'description' => '',
            ],
            [
                'name' => 'Oddział Psychiatryczny',
                'address' => 'ul. Montelupich 7, 31-155 Kraków',
                'phone' => '126301100',
                'email' => 'as_krakow@sw.gov.pl',
                'website' => 'https://www.sw.gov.pl/jednostka/areszt-sledczy-w-krakowie',
                'description' => '',
            ],
            [
                'name' => 'Miejskie Centrum Opieki dla Osób Starszych, Przewlekle Niepełnosprawnych oraz Niesamodzielnych w Krakowie',
                'address' => 'ul. Wielicka 267, 30-663 Kraków',
                'phone' => '124467500',
                'email' => 'zol@zol.krakow.pl',
                'website' => 'https://www.zol-krakow.com.pl',
                'description' => '',
            ],
            [
                'name' => 'Wojewódzki Specjalistyczny Szpital Dziecięcy im. św. Ludwika w Krakowie',
                'address' => 'ul. Strzelecka 2, 31-503 Kraków',
                'phone' => '126198615',
                'email' => 'info@dzieciecyszpital.pl',
                'website' => 'https://www.dzieciecyszpital.pl',
                'description' => '',
            ],
            [
                'name' => '5 Wojskowy Szpital Kliniczny z Polikliniką Samodzielny Publiczny Zakład Opieki Zdrowotnej',
                'address' => 'ul. Wrocławska 1, 30-901 Kraków',
                'phone' => '126308278',
                'email' => 'szpital@5wszk.com.pl',
                'website' => 'https://www.5wszk.com.pl',
                'description' => '',
            ],
            [
                'name' => 'Szpital Uniwersytecki w Krakowie',
                'address' => 'ul. Mikołaja Kopernika 36, 31-501 Kraków',
                'phone' => '124247000',
                'email' => 'info@su.krakow.pl',
                'website' => 'https://www.su.krakow.pl',
                'description' => '',
            ],
            [
                'name' => 'Niepubliczny Zakład Opiekunczy - Leczniczy "Raj-Med." Sp. z o. o.',
                'address' => 'ul. Wł. Sikorskiego 71, 32-540 Trzebinia',
                'phone' => '338432621',
                'email' => 'rajmed@interia.pl',
                'website' => 'https://www.raj-med.pl/lokalizacja',
                'description' => '',
            ],
            [
                'name' => 'Powiatowy Zakład Opiekuńczo-Leczniczy w Grojcu',
                'address' => 'al. Ogrodowa 1, 32-615 Grojec',
                'phone' => '338428136',
                'email' => 'pzol_grojec@poczta.onet.pl',
                'website' => 'https://pzolgrojec.pl/',
                'description' => '',
            ],
            [
                'name' => 'Podhalański Szpital Specjalistyczny im. Jana Pawła II w Nowym Targu',
                'address' => 'ul. Szpitalna 14, 34-400 Nowy Targ',
                'phone' => '182633000',
                'email' => 'sekretariat@pszs.eu',
                'website' => 'https://www.pszs.eu',
                'description' => '',
            ],
            [
                'name' => 'Szpital Specjalistyczny im. J. Śnadeckiego w Nowym Sączu',
                'address' => 'ul. Młyńska 10, 33-300 Nowy Sącz',
                'phone' => '184438877',
                'email' => 'sns@pro.onet.pl',
                'website' => 'https://www.szpitalnowysacz.pl',
                'description' => '',
            ],
            [
                'name' => 'Nowy Szpital w Olkuszu',
                'address' => 'ul. 1000 lecia 13, 32-300 Olkusz',
                'phone' => '412401200',
                'email' => 'sekretariat.olkusz@nowyszpital.pl',
                'website' => 'https://www.nowyszpital.pl',
                'description' => '',
            ],
        ];

        foreach ($facilities as $facilityData) {
            // Parse address to extract city, postal code
            $address = $facilityData['address'];
            $city = '';
            $postalCode = '';
            $province = 'dolnośląskie'; // Default province
            
            // Try to extract postal code (format: 00-000)
            if (preg_match('/(\d{2}-\d{3})\s+(.+)$/u', $address, $matches)) {
                $postalCode = $matches[1];
                $city = trim($matches[2]);
                
                // Determine province based on city or postal code
                $firstTwo = substr($postalCode, 0, 2);
                if (in_array($firstTwo, ['50', '51', '52', '53', '54', '55', '56', '57', '58', '59'])) {
                    $province = 'dolnośląskie';
                } elseif (in_array($firstTwo, ['85', '86', '87', '88', '89'])) {
                    $province = 'kujawsko-pomorskie';
                } elseif (in_array($firstTwo, ['20', '21', '22', '23', '24'])) {
                    $province = 'lubelskie';
                } elseif (in_array($firstTwo, ['65', '66', '67', '68', '69'])) {
                    $province = 'lubuskie';
                } elseif (in_array($firstTwo, ['90', '91', '92', '93', '94', '95', '96', '97', '98', '99'])) {
                    $province = 'łódzkie';
                } elseif (in_array($firstTwo, ['30', '31', '32', '33', '34'])) {
                    $province = 'małopolskie';
                }
            } else {
                // Fallback - use full address as city
                $city = preg_replace('/\r?\n/', ' ', $address);
                $postalCode = '00-000';
            }

            Facility::create([
                'user_id' => $adminUser->id,
                'name' => $facilityData['name'],
                'address' => $facilityData['address'],
                'city' => $city ?: 'Nieznane',
                'province' => $province,
                'postal_code' => $postalCode ?: '00-000',
                'phone' => $facilityData['phone'],
                'email' => $facilityData['email'],
                'website' => $facilityData['website'],
                'description' => $facilityData['description'],
            ]);
        }

        $this->command->info('Successfully seeded ' . count($facilities) . ' facilities.');
    }
}
